# fly.toml file generated for restless-field-1898 on 2022-03-10T13:32:34-07:00

app = "%fly_app_name%-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  build = "Dockerfile"

[env]
  REDIS_PASSWORD = "%fly_redis_password%"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 6379
  protocol = "tcp"
  script_checks = []
  http_checks = []

  [services.concurrency]
    hard_limit = 2500
    soft_limit = 2000
    type = "connections"

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  destination = "/data"
  source = "redis_data"
